version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: portfolio
      MYSQL_USER: system
      MYSQL_PASSWORD: secret
    ports:
      - target: 3306
        published: 3306
        mode: host
    volumes:
      - mysql-data:/var/lib/mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: any
  app:
    image: portfolio_app
    ports:
      - target: 80
        published: 80
        mode: ingress
    secrets:
      - github_pat
    deploy:
      replicas: 1
      restart_policy:
        condition: any

volumes:
  mysql-data:

secrets:
  github_pat:
    external: true